// Congress roster — BSV Group demo.

export const CONGRESS_OPTIONS = [
  {
    id: 'eshre-2026',
    name: 'ESHRE 2026',
    fullName: 'European Society of Human Reproduction and Embryology Annual Meeting 2026',
    location: 'London, UK',
    date: 'Jun 29 – Jul 2, 2026',
    available: true,
  },
  {
    id: 'fogsi-2026',
    name: 'FOGSI 2026',
    fullName: 'Federation of Obstetric and Gynaecological Societies of India Annual Congress 2026',
    location: 'Hyderabad, India',
    date: 'Jan 15–18, 2026',
    available: true,
  },
  {
    id: 'trend-2025-2026',
    name: 'Trend: FOGSI 2025 → 2026',
    fullName: 'Sentiment trend FOGSI 2025 to FOGSI 2026',
    location: '—',
    date: '—',
    available: true,
    isTrend: true,
  },
  {
    id: 'india-ivf-2026',
    name: 'India IVF Summit 2026',
    fullName: 'India IVF and Fertility Summit 2026',
    location: 'Mumbai, India',
    date: 'Mar 2026',
    available: false,
    comingSoon: true,
  },
  {
    id: 'aogu-2026',
    name: 'AOGU 2026',
    fullName: 'Association of Obstetricians and Gynaecologists of Uganda Annual Congress',
    location: 'TBD',
    date: 'Sep 2026',
    available: false,
    comingSoon: true,
  },
  {
    id: 'ecsacog-2026',
    name: 'ECSACOG 2026',
    fullName: 'East, Central and Southern Africa College of Obstetricians and Gynaecologists Congress',
    location: 'TBD',
    date: 'Nov 2026',
    available: false,
    comingSoon: true,
  },
  {
    id: 'nabicon-2026',
    name: 'NABICON 2026',
    fullName: 'National Burns and Wound Care Congress 2026',
    location: 'India',
    date: 'Oct 2026',
    available: false,
    comingSoon: true,
  },
];
