// Actionable insights — BSV Group demo.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'rFSH narrative winning at ESHRE — urinary FSH rebuttal needed urgently',
    priority: 'High',
    lpRefs: ['LP3', 'LP5'], moRefs: ['MO3', 'MO5'],
    recurrence: 4,
    recency: '2026-07',
    summary: 'Multiple KOLs returning from ESHRE 2026 (London) have referenced recombinant FSH superiority messaging from Merck and Organon symposia. Three IVF centre directors have explicitly asked BSV MSLs for clinical equivalence data. Without a fast rebuttal, prescribing inertia toward rFSH will solidify in Tier 1 IVF centres.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'IVF specialist', location: 'Mumbai (post-ESHRE 2026)', quote: 'The Gonal-f satellite had strong data. I need to see something from BSV before I shift my PCOS protocol.', date: '2026-07-05' },
      { type: 'MSL interaction', role: 'Reproductive endocrinologist', location: 'Bangalore', quote: 'If you can show me Cochrane-level evidence, I\'ll stay with HMG. Otherwise I have to follow ESHRE consensus.', date: '2026-07-02' },
      { type: 'MSL interaction', role: 'IVF lab director', location: 'Delhi', quote: 'Gonal-f reps are citing batch consistency. Can you show me batch QC data for Humog?', date: '2026-06-28' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'Anti-D compliance crisis in Tier 2/3 — cost and stock gaps identified',
    priority: 'High',
    lpRefs: ['LP1'], moRefs: ['MO1'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'MSL field reports across three regions consistently flag out-of-pocket cost (₹800–1,200 per injection) and irregular hospital stock as the primary barriers to Anti-D compliance in Tier 2/3 settings. Patients who self-pay are choosing to defer or forgo prophylaxis. A structured patient support or institutional bulk-supply programme is urgently needed.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community obstetrician', location: 'Nashik', quote: 'My patients know they need it but they ask if they can wait. The answer is no, but I can\'t pay for it myself.', date: '2026-06-14' },
      { type: 'MSL interaction', role: 'District hospital OBGYN', location: 'Ludhiana', quote: 'We ran out of Anti-D stock for 3 weeks last quarter. Those patients are now sensitised.', date: '2026-06-07' },
      { type: 'Ad board', role: 'Maternal health specialist', location: 'Virtual', quote: 'If BSV offered a hospital supply programme for Tier 3, they would own this segment entirely.', date: '2026-05-28' },
    ],
    status: 'Validated',
    confidenceScore: 0.88,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'Luprodex Depot 3-month protocol gaining traction — data needed to support shift',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-07',
    summary: 'Three top-tier KOLs including Dr. Rishma Dhillon Pai and Dr. Narendra Malhotra have independently shifted their endometriosis practice toward shorter GnRH agonist cycles with add-back therapy, citing patient quality-of-life and bone density concerns. BSV lacks a BSV-branded 3-month protocol algorithm that MSLs can distribute to support this shift.',
    sourceInsights: [
      { type: 'Advisory board', role: 'Reproductive medicine specialist', location: 'Mumbai', quote: 'I use Luprodex 3-month depot now as default for stage II endo. But I need something to hand nurses who ask about the protocol.', date: '2026-07-01' },
      { type: 'MSL interaction', role: 'IVF-linked gynaecologist', location: 'Agra', quote: 'Six months of bone loss is hard to justify anymore. Show me a 3-month add-back study and I\'ll formalise the protocol.', date: '2026-06-22' },
    ],
    status: 'Validated',
    confidenceScore: 0.84,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'Oncofertility — new KOL segment opening for Luprodex',
    priority: 'Medium',
    lpRefs: ['LP4'], moRefs: ['MO4'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'Gynecologic oncologists at HCG (Bangalore) and RGCI (Delhi) are asking BSV MSLs for ovarian protection data on leuprolide during chemotherapy. This is a net-new physician segment for BSV and represents an emerging entry point for Luprodex into oncology. Current MSL briefing materials do not include the oncofertility indication.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Gynecologic oncologist', location: 'Bangalore', quote: 'I want to protect ovarian function before CHOP. Can Luprodex do that? I need the literature.', date: '2026-06-25' },
      { type: 'MSL interaction', role: 'Medical oncologist', location: 'Delhi', quote: 'We have younger breast cancer patients asking about fertility preservation. Who covers this at BSV?', date: '2026-06-18' },
    ],
    status: 'Triaged',
    confidenceScore: 0.76,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Dr. Meenakshi Sundaram shifting toward recombinant GnRH analogues',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'DIVERGENCE ALERT: Dr. S. Meenakshi Sundaram (Apollo Chennai) attended a GSK-sponsored advisory board in March 2026 and has since begun recommending newer recombinant GnRH analogues over BSV\'s Goserelin and Luprodex. Alignment score has declined from 74 to 52. Requires priority MSL intervention before she formalises her practice change.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Dr. Meenakshi Sundaram, Apollo Chennai', location: 'Chennai', quote: 'The data from the GSK advisory was compelling on the purity profile. I\'m giving the new analogue a 6-month trial in my practice.', date: '2026-04-02' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.79,
    provenance: 'synthesized',
  },
  {
    id: 'AI6',
    title: 'Minimal stimulation IVF — HMG positioning gap identified by ISAR KOLs',
    priority: 'Medium',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'ISAR members at the India IVF Summit flagged that BSV has no minimal stimulation protocol messaging, despite HMG being the natural fit for mild stimulation IVF. Two PCOS specialists specifically asked for minimal stimulation clinical data for HMG. MINICOV trial interim results (OHSS 2.4% vs 8.1%) are ready to use in MSL exchanges.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'PCOS specialist', location: 'India IVF Summit 2026', quote: 'For mild stimulation in PCOS, HMG makes biological sense. BSV should be leading this conversation.', date: '2026-03-18' },
    ],
    status: 'Validated',
    confidenceScore: 0.72,
    provenance: 'synthesized',
  },
  {
    id: 'AI7',
    title: 'Batch consistency questions — BSV quality assurance response needed',
    priority: 'Medium',
    lpRefs: ['LP3', 'LP5'], moRefs: ['MO3', 'MO5'],
    recurrence: 2,
    recency: '2026-07',
    summary: 'Three IVF lab directors at high-volume centres have independently asked BSV MSLs for batch-to-batch consistency data for Humog (HMG) and Diva FSH. This is a direct response to Merck\'s Gonal-f messaging at ESHRE 2026. A QA one-pager that MSLs can distribute is essential to neutralise this competitive argument.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'IVF laboratory director', location: 'Delhi', quote: 'Gonal-f reps claim their consistency is superior. I need to see your batch QC certificates.', date: '2026-07-03' },
    ],
    status: 'Captured',
    confidenceScore: 0.68,
    provenance: 'synthesized',
  },
];
